# Generated by Django 4.0.3 on 2022-05-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='term_of_service',
        ),
    ]
