# Generated by Django 4.0.3 on 2022-05-24 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_term_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='whishlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(blank=True, default=None, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
