# Generated by Django 4.0.3 on 2022-05-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_info',
            field=models.BooleanField(default=False),
        ),
    ]
