# Generated by Django 4.0.3 on 2022-05-24 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_product_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pointure',
            field=models.PositiveBigIntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.size'),
        ),
    ]
